### ISSUE TITLE
There is a balance in PDEX but when the user tries to delete the trading account(extension), the "confirm transaction" pop-up displayed your  balance is not enough to pay the fee

### ISSUE THREAD

**Issue by Hildajose** [Polkadex-Substrate/Polkadex-Orderbook-Frontend#1265] opened 2024-05-16 05:34 UTC
# 📝 Bug Description
There is a balance in PDEX but when the user tries to delete the trading account(extension), the "confirm transaction" pop-up displayed your  balance is not enough to pay the fee

## 🤔 Expected Behavior
The user should able to delete the trading account if the user has a balance

## 😯 Current Behavior
The user not able to delete the trading account(extension) if user has the balance
account

https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/assets/148185509/43d4a26c-4b3d-4583-9f92-b60a8570f1d5

## 🔎 Steps to Reproduce

1. Delete the trading account(extension)
2. displayed "Register funding account" button
3. Click "Register funding account" button 
4. automatically log out from the account
5. login with funding account
6.  Click "Register funding account" button 
7. "sign and submit" button
8. In "confirm transaction" pop-up displays "your  balance is not enough to pay the fee"
9. But user can view that trading account displayed in the Registers trading accounts button
10. Verify the user try to delete that account

## 🌍 Your Environment

| Software         | Version(s)                  |
| ---------------- | --------------------------- |
| Project/Package  |                             |
| Browser          | []Chrome []Firefox []Safari |
| Operating System | []Windows []MacOS []Linux   |

**Comment by ap211unitech** [comment] 2024-05-16 05:40
Duplicate of https://github.com/Polkadex-Substrate/Polkadex-Orderbook-Frontend/issues/1264

**Closed as completed** 2024-05-16 10:35 UTC
Labels: wontfix, A0-PleaseReview, QA-Bug
